name: Build Linux App

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Normalise platform tag
        id: normalise_platform
        shell: bash
        run: |
          tag=$(echo ${{ matrix.platform }} | sed -e 's/\//_/g')
          echo "tag=$tag" >> "$GITHUB_OUTPUT"
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install wails
        shell: bash
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Install Ubuntu prerequisites
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libfuse-dev libfuse2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Setup pnpm
        shell: bash
        run: curl -fsSL https://get.pnpm.io/install.sh | sudo sh -
      - name: Build app
        shell: bash
        run: |
          mkdir -p build/bin
          wails build -o build/bin/asmblive_${{ steps.normalise_platform.outputs.tag }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: asmblive_${{ steps.normalise_platform.outputs.tag }}
          path: build/bin/asmblive_${{ steps.normalise_platform.outputs.tag }}
