name: Build Linux App

on: [push]

jobs:
  Build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform:
          - windows/amd64
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Normalise platform tag
        id: normalise_platform
        shell: bash
        run: |
          tag=$(echo ${{ matrix.platform }} | sed -e 's/\//_/g')
          echo "tag=$tag" >> "$GITHUB_OUTPUT"
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install wails
        shell: bash
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Build app
        shell: bash
        run: |
          wails build -o asmblive_${{ steps.normalise_platform.outputs.tag }}
          wails build -debug -o asmblive_${{ steps.normalise_platform.outputs.tag }}_debug
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: asmblive_${{ steps.normalise_platform.outputs.tag }}
          path: build/bin/asmblive_${{ steps.normalise_platform.outputs.tag }}
      - name: Upload debug artifact
        uses: actions/upload-artifact@v4
        with:
          name: asmblive_${{ steps.normalise_platform.outputs.tag }}_debug
          path: build/bin/asmblive_${{ steps.normalise_platform.outputs.tag }}_debug
